export const products = [
  {
    _id: "1",
    name: "Wireless Noise-Cancelling Headphones",
    price: 169,
    image: "/products/headphones.png",
  },
  {
    _id: "2",
    name: "Compact 10000mAh Power Bank",
    price: 67,
    image: "/products/powerbank.png",
  },
  {
    _id: "3",
    name: "Mechanical Keyboard",
    price: 109,
    image: "/products/keyboard.png",
  },
  {
    _id: "4",
    name: "Wireless Ergonomic Mouse",
    price: 49,
    image: "/products/mouse.png",
  },
];
export const flashDeals = [
  {
    id: 1,
    name: "MiniBuds Pro",
    image: "/products/earbuds.png",
    originalPrice: 99.99,
    salePrice: 39.99,
    discount: 20,
    rating: 4.5,
    reviews: 128,
    endsIn: 5 * 3600 + 45 * 60 + 63,
  },
  {
    id: 2,
    name: "PowerCore 20K",
    image: "/products/powerbank.png",
    originalPrice: 40.99,
    salePrice: 37.49,
    discount: 25,
    rating: 4.8,
    reviews: 342,
    endsIn: 6 * 3600 + 72 * 60 + 22,
  },
  {
    id: 3,
    name: "KeyTac Mechanical Keyboard",
    image: "/products/keyboard.png",
    originalPrice: 89.99,
    salePrice: 109.49,
    discount: 25,
    rating: 4.7,
    reviews: 89,
    endsIn: 8 * 3600 + 72 * 60 + 59,
  },
  {
    id: 4,
    name: "CratMTHX Wireless",
    image: "/products/mouse.png",
    originalPrice: 99.99,
    salePrice: 49.99,
    discount: 15,
    rating: 5,
    reviews: 201,
    endsIn: 8 * 3600 + 40 * 60 + 66,
  },
  {
    id: 5,
    name: "NoiseFree 500",
    image: "/products/headphones.png",
    originalPrice: 129.99,
    salePrice: 79.99,
    discount: 38,
    rating: 4.6,
    reviews: 410,
    endsIn: 3 * 3600 + 20 * 60 + 10,
  },
  {
    id: 6,
    name: "TurboCharge 65W",
    image: "/products/charger.png",
    originalPrice: 49.99,
    salePrice: 29.99,
    discount: 40,
    rating: 4.9,
    reviews: 537,
    endsIn: 10 * 3600 + 5 * 60 + 33,
  },
];

export const bundles = [
  {
    id: 1,
    name: "Work From Home Bundle",
    description: "Wireless Mechanical Keyboard + Mouse",
    originalPrice: 299.95,
    salePrice: 199.0,
    savings: 100.95,
    rating: 4.5,
    image: "/products/keyboard.png",
  },
  {
    id: 2,
    name: "Audio Bundle",
    description: "Wireless Charger + Earbuds",
    originalPrice: 204.95,
    salePrice: 99.99,
    savings: 104.95,
    rating: 4.7,
    image: "/products/earbuds.png",
  },
  {
    id: 3,
    name: "Power User Bundle",
    description: "Power Bank 20K + 65W Charger + Cable",
    originalPrice: 159.97,
    salePrice: 89.99,
    savings: 69.98,
    rating: 4.8,
    image: "/products/powerbank.png",
  },
];
